#!/usr/bin/env python3
"""Generate a data dictionary + provenance manifest for the dataset (audit #4).

The original Excel -> CSV conversion is currently an external manual step, so this
script pins the dataset contract that the pipeline actually consumes: it records a
SHA-256 checksum, shape, and a per-column profile (dtype, missing fraction, inferred
unit, numeric range / categorical levels) for each CSV. Re-run it whenever the
dataset changes; commit the outputs so dataset provenance is reproducible.

Outputs:
    data/dataset_manifest.json   — checksums, shapes, schema (machine-readable)
    data/DATA_DICTIONARY.md      — human-readable column dictionary

Usage:
    PYTHONPATH=src python scripts/build_data_dictionary.py
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Dict, List

import numpy as np
import pandas as pd

DEFAULT_INPUTS = [
    "data/SEC_SYN_with_features.csv",
    "data/SEC_SYN_with_features_enriched.csv",
]


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _infer_unit(column: str) -> str:
    # Units in this dataset are embedded after the last comma, e.g. "E0, кДж/моль".
    if "," in column:
        return column.rsplit(",", 1)[1].strip()
    return ""


def _profile_column(series: pd.Series) -> Dict[str, object]:
    n = len(series)
    missing = int(series.isna().sum())
    info: Dict[str, object] = {
        "dtype": str(series.dtype),
        "missing": missing,
        "missing_frac": round(missing / n, 4) if n else None,
        "n_unique": int(series.nunique(dropna=True)),
        "unit": _infer_unit(str(series.name)),
    }
    numeric = pd.to_numeric(series, errors="coerce")
    if numeric.notna().mean() > 0.8:  # treat as numeric
        info["kind"] = "numeric"
        info["min"] = float(np.nanmin(numeric)) if numeric.notna().any() else None
        info["max"] = float(np.nanmax(numeric)) if numeric.notna().any() else None
        info["mean"] = float(np.nanmean(numeric)) if numeric.notna().any() else None
        info["std"] = float(np.nanstd(numeric)) if numeric.notna().any() else None
        if numeric.notna().any():
            info["zero_frac"] = round(float((numeric == 0).mean()), 4)
    else:
        info["kind"] = "categorical"
        levels = series.dropna().astype(str).value_counts().head(20)
        info["levels"] = {str(k): int(v) for k, v in levels.items()}
    return info


def profile_csv(path: Path) -> Dict[str, object]:
    df = pd.read_csv(path)
    return {
        "path": str(path),
        "sha256": _sha256(path),
        "rows": int(df.shape[0]),
        "cols": int(df.shape[1]),
        "columns": {col: _profile_column(df[col]) for col in df.columns},
    }


def render_markdown(manifest: Dict[str, object]) -> str:
    lines: List[str] = ["# Data dictionary", ""]
    lines.append(f"Generated by `scripts/build_data_dictionary.py` (audit #4). Timestamp: {manifest.get('generated_at', 'n/a')}.")
    lines.append("")
    lines.append("> Note: the original Excel → CSV ingestion is an external manual step. "
                 "This dictionary pins the CSV contract the pipeline consumes; the SHA-256 "
                 "checksums below let you detect any silent change to a dataset file.")
    lines.append("")
    for ds in manifest["datasets"]:
        lines.append(f"## `{ds['path']}`")
        lines.append("")
        lines.append(f"- rows: **{ds['rows']}**, cols: **{ds['cols']}**")
        lines.append(f"- sha256: `{ds['sha256']}`")
        lines.append("")
        lines.append("| column | kind | unit | missing% | range / levels |")
        lines.append("|---|---|---|---|---|")
        for col, info in ds["columns"].items():
            miss = f"{(info['missing_frac'] or 0) * 100:.1f}%"
            if info["kind"] == "numeric":
                rng = f"[{info.get('min')}, {info.get('max')}]"
                if info.get("zero_frac"):
                    rng += f", zeros={info['zero_frac'] * 100:.0f}%"
            else:
                lv = list(info.get("levels", {}).keys())
                rng = ", ".join(lv[:8]) + (" …" if len(lv) > 8 else "")
            unit = info.get("unit") or "—"
            lines.append(f"| `{col}` | {info['kind']} | {unit} | {miss} | {rng} |")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Build dataset data dictionary + manifest.")
    parser.add_argument("--inputs", nargs="*", default=DEFAULT_INPUTS)
    parser.add_argument("--manifest", default="data/dataset_manifest.json")
    parser.add_argument("--dictionary", default="data/DATA_DICTIONARY.md")
    parser.add_argument("--generated-at", default="", help="Optional ISO timestamp to stamp.")
    args = parser.parse_args()

    datasets = []
    for raw in args.inputs:
        path = Path(raw)
        if not path.exists():
            print(f"  skip (missing): {path}")
            continue
        print(f"  profiling: {path}")
        datasets.append(profile_csv(path))

    manifest = {"generated_at": args.generated_at, "datasets": datasets}
    Path(args.manifest).parent.mkdir(parents=True, exist_ok=True)
    with open(args.manifest, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, ensure_ascii=False, indent=2)
    with open(args.dictionary, "w", encoding="utf-8") as fh:
        fh.write(render_markdown(manifest))
    print(f"Wrote {args.manifest} and {args.dictionary} for {len(datasets)} dataset(s).")


if __name__ == "__main__":
    main()
